# Generated by Django 3.2.25 on 2026-08-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='core/pdf_cv/', verbose_name='Certificado PDF')),
                ('archivo_pdf_en', models.FileField(blank=True, null=True, upload_to='core/pdf_cv/', verbose_name='Certificado PDF')),
                ('archivo_pdf_pt_br', models.FileField(blank=True, null=True, upload_to='core/pdf_cv/', verbose_name='Certificado PDF')),
                ('archivo_pdf_it', models.FileField(blank=True, null=True, upload_to='core/pdf_cv/', verbose_name='Certificado PDF')),
                ('archivo_pdf_fr', models.FileField(blank=True, null=True, upload_to='core/pdf_cv/', verbose_name='Certificado PDF')),
                ('archivo_pdf_es', models.FileField(blank=True, null=True, upload_to='core/pdf_cv/', verbose_name='Certificado PDF')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cronomarcador de modificación')),
            ],
            options={
                'verbose_name': 'PDF CV',
                'verbose_name_plural': 'PDF CVs',
            },
        ),
    ]
