"""
Django settings for webpersonal project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url



load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

json_path = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')


if json_path and os.path.exists(json_path):
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = json_path
else:
    pass


# Buscamos una variable llamada IS_DOCKER que definiremos en el Dockerfile
IS_DOCKER = os.environ.get('IS_DOCKER', 'False') == 'True'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage' if IS_DOCKER else 'django.core.files.storage.FileSystemStorage'

# Definimos variables globales que se poblarán si IS_DOCKER es True
AWS_ACCESS_KEY_ID = os.environ.get('SUPABASE_ACCESS_KEY') if IS_DOCKER else None
AWS_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_SECRET') if IS_DOCKER else None
AWS_STORAGE_BUCKET_NAME = 'media' if IS_DOCKER else None
AWS_S3_ENDPOINT_URL = f"https://{os.environ.get('SUPABASE_PROJECT_ID')}.supabase.co/storage/v1/s3" if IS_DOCKER else None
AWS_S3_REGION_NAME = 'sa-east-1' if IS_DOCKER else None
AWS_S3_ADDRESSING_STYLE = "path" if IS_DOCKER else None
AWS_S3_SIGNATURE_VERSION = "s3v4" if IS_DOCKER else None
AWS_S3_CUSTOM_DOMAIN = f"{os.environ.get('SUPABASE_PROJECT_ID')}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}" if IS_DOCKER else None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#Leo config.ini file

# SECURITY WARNING: don't run with debug turned on in production!

#SEARCH FOR LOCAL SETTINGS

if IS_DOCKER:
    # CONFIGURACIÓN PARA GOOGLE CLOUD / DOCKER
    print("--- Corriendo en MODO DOCKER (Supabase) ---")
    # Aquí puedes forzar configuraciones de producción
    DEBUG = True
    ALLOWED_HOSTS = ["*"]
    SECRET_KEY = os.environ.get('SECRET_KEY')
else:
    # CONFIGURACIÓN PARA PYTHONANYWHERE / LOCAL
    print("--- Corriendo en MODO LOCAL/PYTHONANYWHERE (SQLite) ---")
    try:
        from .local_settings import *
    except ImportError:
        DEBUG = os.environ.get('DEBUG') == 'True'
        ALLOWED_HOSTS = ["AgustinFara.pythonanywhere.com"]           
        SECRET_KEY = os.environ.get('SECRET_KEY')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'cv.apps.CvConfig',
    'portfolio.apps.PortfolioConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webpersonal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webpersonal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


if IS_DOCKER:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DB_URL'),
            conn_max_age=600,
            ssl_require=False  # Esto es lo que activa el cifrado
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ('en', _('English')),
    ('pt-br', _('Portuguese')),
    ('it', _('Italian')),
    ('fr', _('French')),
    ('es', _('Spanish')),
)


LANGUAGE_CODE = 'es-AR'


TIME_ZONE = 'America/Argentina/Buenos_Aires' 

USE_TZ = True

USE_I18N = True

USE_L10N = True



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#LOCALE_PATHS = (BASE_DIR / 'locale')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# Configuración de archivos estáticos para producción
if IS_DOCKER:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = ( BASE_DIR / 'static')

    #Media Files
    MEDIA_URL = '/media/'
    MEDIA_ROOT = ( BASE_DIR / 'media')


