# Generated by Django 3.2.25 on 2026-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='courses', verbose_name='Imagen')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cronomarcador de modificación')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='courses/certificates/', verbose_name='Certificado PDF')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cronomarcador de modificación')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link para más información')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-date'],
            },
        ),
    ]
