# Generated by Django 3.2.25 on 2026-08-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_pt_br',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt_br',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
