# Generated by Django 3.2.25 on 2026-08-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20260803_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_repo',
            field=models.URLField(blank=True, null=True, verbose_name='Link Repositorio'),
        ),
    ]
