name: Deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Construir imagen
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mi-repo-web/mi-web-app:v3 || true

      - name: Desplegar en Cloud Run
        run: |      
          gcloud run deploy mi-web-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mi-repo-web/mi-web-app:v3 \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars DB_URL=${{ secrets.DB_URL }},SECRET_KEY=${{ secrets.SECRET_KEY }},IS_DOCKER=${{ secrets.IS_DOCKER }},SUPABASE_ACCESS_KEY=${{ secrets.SUPABASE_ACCESS_KEY }},SUPABASE_SECRET=${{ secrets.SUPABASE_SECRET }},SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID }}