# Generated by Django 3.2.25 on 2026-06-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_svg', models.TextField(help_text='Pega aquí el código SVG')),
                ('created', models.DateTimeField(auto_now_add=True,
                 verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True,
                 verbose_name='Cronomarcador de modificación')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='work', verbose_name='Imagen')),
                ('datestart', models.DateField(verbose_name='Fecha de comienzo')),
                ('datefinish', models.DateField(
                    verbose_name='Fecha de finalización')),
                ('created', models.DateTimeField(auto_now_add=True,
                 verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True,
                 verbose_name='Cronomarcador de modificación')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-datefinish'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200,
                 null=True, verbose_name='Empresa Cliente')),
                ('image', models.ImageField(blank=True, null=True,
                 upload_to='work', verbose_name='Imagen Cliente')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='Descripción')),
                ('datestart', models.DateField(verbose_name='Fecha de comienzo')),
                ('datefinish', models.DateField(
                    verbose_name='Fecha de finalización')),
                ('created', models.DateTimeField(auto_now_add=True,
                 verbose_name='Cronomarcador de creación')),
                ('updated', models.DateTimeField(auto_now=True,
                 verbose_name='Cronomarcador de modificación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='cv.work', verbose_name='Empresa Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-datefinish'],
            },
        ),
    ]
