# Generated by Django 3.2.25 on 2026-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': [
                '-datestart'], 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AddField(
            model_name='work',
            name='is_current',
            field=models.BooleanField(
                default=False, verbose_name='¿Es mi trabajo actual?'),
        ),
        migrations.AlterField(
            model_name='work',
            name='datefinish',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='Fecha de finalización'),
        ),
    ]
