# Generated by Django 3.2.25 on 2026-06-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20260609_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['order'], 'verbose_name': 'Tecnología', 'verbose_name_plural': 'Tecnologías'},
        ),
    ]
