# Generated by Django 3.2.25 on 2026-08-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_technology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de categoría'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de categoría'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de categoría'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de categoría'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de categoría'),
        ),
    ]
